name: Vaciar Base de Datos (Mundial PRODE)

on:
  workflow_dispatch:
    # Solo ejecución manual

jobs:
  clear:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ejecutar Limpieza
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: node scripts/clear-db.js
